apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: appp_db_1
spec:
  ports:
    - port: 5432
      targetPort: 5432
      name: db
  selector:
    app: appp_db_1
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    app: appp_db_1
spec:
  selector:
    matchLabels:
      app: appp_db_1
  template:
    metadata:
      labels:
        app: appp_db_1
    spec:
      containers:
      - name: db
        image: dockersamples/k8s-wordsmith-db
        ports:
        - containerPort: 5432
          name: db
---
apiVersion: v1
kind: Service
metadata:
  name: words
  labels:
    app: words-api
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: api
  selector:
    app: appp_web_1
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: appp_web_1
spec:
  ports:
    - port: 8081
      targetPort: 80
      name: web
  selector:
    app: appp_web_1
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: apppweb
spec:
  selector:
    matchLabels:
      app: apppweb
  template:
    metadata:
      labels:
        app: apppweb
    spec:
      containers:
      - name: web
        image: dockersamples/k8s-wordsmith-web
        ports:
        - containerPort: 80
          name: apppweb